### ISSUE TITLE
Error requiring the component

### ISSUE THREAD

**Issue by ciaoben** [iaalm/react-qrcode#1]
Simply requiring with `require('react-qrcode')`

```
ERROR in ./~/react-qrcode/QRcode.js
Module parse failed: /Users/ben/pro/qbvault/node_modules/react-qrcode/QRcode.js Line 89: Unexpected token <
You may need an appropriate loader to handle this file type.
|   render: function() {
|       return (
|               <div id='qrcode' ref='qrcode' />
|       )
|   }
 @ ./app/assets/javascripts/components/OTP.js.jsx 7:13-36
H
```

**Comment by iaalm** [comment]
This code is design for web,so you need to refer it with a  

> ```
> <script type="text/jsx">
> ```

tag in html.You can see http://facebook.github.io/react/docs/getting-started.html for more information.

**Comment by matthewwithanm** [comment]
@iaalm The issue is that the library is using JSX. That means all users are going to have to compile it themselves 😞

It would be better to publish the compiled version to npm. (If you don't want to set up compilation stuff, you could just replace that line with `React.createElement('div', {id: 'qrcode', ref: 'qrcode'})`.)

**Comment by iaalm** [comment]
That's good. Thank @matthewwithanm :smiley:

**Comment by JounQin** [comment]
@ciaoben @matthewwithanm You can try `react-qrcode@0.2.0` which is rewritten from scratch now.
